locale                   : "en-US"
title                    : "Connor Esterwood"
title_separator          : "-"
name                     : &name "Connor Esterwood"
description              : &description "PHD Candidate at UMSI"
url                      : https://cte.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "cte.github.io"
theme: minimal-mistakes-jekyll